USE SPRING;

CREATE TABLE IF NOT EXISTS ITEM(
	ITEM_ID INTEGER(5) AUTO_INCREMENT,
	ITEM_NAME VARCHAR(20),
	PRICE INTEGER(6),
	DESCRIPTION VARCHAR(50),
	PICTURE_URL VARCHAR(20),
	PRIMARY KEY (ITEM_ID)
);

ALTER TABLE ITEM ADD COLUMN PICTURE LONGBLOB;

TRUNCATE TABLE SALE_LINE;
TRUNCATE TABLE SALE;



/*

create sequence sequence01 start with 1 increment by 1 minvalue 1 maxvalue 99999999;

CREATE TABLE ITEM(
	ITEM_ID NUMBER,
	ITEM_NAME VARCHAR2(20),
	PRICE NUMBER,
	DESCRIPTION VARCHAR2(50),
	PICTURE_URL VARCHAR2(20),
	PRIMARY KEY (ITEM_ID)
);

ALTER TABLE ITEM ADD (PICTURE BLOB);
*/

/*

CREATE TABLE ITEM2(
	ITEM_ID NUMBER,
	ITEM_NAME VARCHAR2(20),
	PRICE NUMBER,
	DESCRIPTION VARCHAR2(50),
	PICTURE_URL VARCHAR2(20),
	PRIMARY KEY (ITEM_ID)
);

ALTER TABLE ITEM2 ADD (PICTURE BLOB);
*/